# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190429_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='正文必须为MarkDown格式', verbose_name='正文'),
        ),
    ]
